name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Assuming LXD is already installed and initialized
    # If not, uncomment the following steps
    # - name: Install LXD
    #   run: sudo apt-get install -y lxd

    # - name: Initialize LXD
    #   run: sudo lxd init --auto

    - name: Launch LXD container
      run: |
        lxc launch images:debian/11/amd64 ci-container
        sleep 10

    - name: Install dependencies in container
      run: |
        lxc exec ci-container -- apt-get update
        lxc exec ci-container -- apt-get install -y build-essential nodejs npm

    - name: Copy source code to container
      run: lxc file push -r . ci-container/root/project

    - name: Build and test inside container
      run: |
        lxc exec ci-container -- /bin/bash -c "cd /root/project && npm install"
        lxc exec ci-container -- /bin/bash -c "cd /root/project && npm run build"

    - name: Clean up container
      if: always()
      run: lxc delete -f ci-container
